name: My First Github Action!

on:
  push:
    branches:
      - main

jobs:
  hello-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello World Message
        run: echo "Welcome to my world!"

      - name: Create a file and add some data
        run: echo "Welcome to GitHub Action!" > test.txt

      - name: To see data in test file
        run: cat test.txt

      - name: List all the files in directory
        run: ls -latr

  window-job:
    runs-on: windows-latest

    steps:
      - name: check the hostname
        shell: pwsh
        run: hostname

      - name: Add some data in files
        shell: pwsh
        run: |
          "Hello window server" | Out-File test.txt

      - name: see data in test file
        shell: pwsh
        run: |
          Get-Content test.txt

  



  


