name: Checkout github action lab

on:
  push:
    branches:
      - main

jobs:
  checkout-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git repo
        uses: actions/checkout@v4

      - name: present working directory
        run: pwd

      - name: List the files in present directory
        run: ls -latr

      - name: show git status
        run: git status

      - name: show git branch
        run: git branch
